from ccxt.base.types import Entry


class ImplicitAPI:
    public_get_tickers = publicGetTickers = Entry('tickers/', 'public', 'GET', {})
    public_get_tickers_pair = publicGetTickersPair = Entry('tickers/{pair}/', 'public', 'GET', {})
    public_get_orders_level_3 = publicGetOrdersLevel3 = Entry('orders/level-3/', 'public', 'GET', {})
    public_get_orders_level_2 = publicGetOrdersLevel2 = Entry('orders/level-2/', 'public', 'GET', {})
    public_get_trades = publicGetTrades = Entry('trades/', 'public', 'GET', {})
    public_get_currencies = publicGetCurrencies = Entry('currencies/', 'public', 'GET', {})
    public_get_pairs = publicGetPairs = Entry('pairs/', 'public', 'GET', {})
    private_get_book_summaries = privateGetBookSummaries = Entry('book/summaries/', 'private', 'GET', {})
    private_get_book_estimate_price_pair = privateGetBookEstimatePricePair = Entry('book/estimate-price/{pair}/', 'private', 'GET', {})
    private_get_book_orders_level_3 = privateGetBookOrdersLevel3 = Entry('book/orders/level-3/', 'private', 'GET', {})
    private_get_book_orders_level_2 = privateGetBookOrdersLevel2 = Entry('book/orders/level-2/', 'private', 'GET', {})
    private_get_user_balances = privateGetUserBalances = Entry('user/balances/', 'private', 'GET', {})
    private_get_user_fees_and_limits = privateGetUserFeesAndLimits = Entry('user/fees-and-limits/', 'private', 'GET', {})
    private_get_user_statement = privateGetUserStatement = Entry('user/statement/', 'private', 'GET', {})
    private_get_user_statement_currency_code = privateGetUserStatementCurrencyCode = Entry('user/statement/{currency_code}/', 'private', 'GET', {})
    private_get_user_trades = privateGetUserTrades = Entry('user/trades/', 'private', 'GET', {})
    private_get_orders = privateGetOrders = Entry('orders/', 'private', 'GET', {})
    private_get_orders_open = privateGetOrdersOpen = Entry('orders/open/', 'private', 'GET', {})
    private_get_orders_id = privateGetOrdersId = Entry('orders/{id}/', 'private', 'GET', {})
    private_get_orders_by_external_id_external_id = privateGetOrdersByExternalIdExternalId = Entry('orders/by-external-id/{external_id}/', 'private', 'GET', {})
    private_get_deposits = privateGetDeposits = Entry('deposits/', 'private', 'GET', {})
    private_get_withdrawals = privateGetWithdrawals = Entry('withdrawals/', 'private', 'GET', {})
    private_get_withdrawals_estimate_fee_currency_code = privateGetWithdrawalsEstimateFeeCurrencyCode = Entry('withdrawals/estimate-fee/{currency_code}/', 'private', 'GET', {})
    private_get_wallets_is_internal = privateGetWalletsIsInternal = Entry('wallets/is-internal/', 'private', 'GET', {})
    private_get_wallets_balance = privateGetWalletsBalance = Entry('wallets/balance/', 'private', 'GET', {})
    private_get_wallets_balance_date = privateGetWalletsBalanceDate = Entry('wallets/balance/{date}/', 'private', 'GET', {})
    private_post_orders = privatePostOrders = Entry('orders/', 'private', 'POST', {})
    private_post_withdrawals = privatePostWithdrawals = Entry('withdrawals/', 'private', 'POST', {})
    private_post_transactions_sync = privatePostTransactionsSync = Entry('transactions/sync/', 'private', 'POST', {})
    private_post_ticket = privatePostTicket = Entry('ticket/', 'private', 'POST', {})
    private_delete_orders = privateDeleteOrders = Entry('orders/', 'private', 'DELETE', {})
    private_delete_orders_by_external_id = privateDeleteOrdersByExternalId = Entry('orders/by-external-id/', 'private', 'DELETE', {})
    private_delete_orders_all = privateDeleteOrdersAll = Entry('orders/all/', 'private', 'DELETE', {})
