<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class ripio extends \ccxt\Exchange {
    public function public_get_tickers($params = array()) {
        return $this->request('tickers/', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_tickers_pair($params = array()) {
        return $this->request('tickers/{pair}/', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_orders_level_3($params = array()) {
        return $this->request('orders/level-3/', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_orders_level_2($params = array()) {
        return $this->request('orders/level-2/', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_trades($params = array()) {
        return $this->request('trades/', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_currencies($params = array()) {
        return $this->request('currencies/', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_pairs($params = array()) {
        return $this->request('pairs/', 'public', 'GET', $params, null, null, array());
    }
    public function private_get_book_summaries($params = array()) {
        return $this->request('book/summaries/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_book_estimate_price_pair($params = array()) {
        return $this->request('book/estimate-price/{pair}/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_book_orders_level_3($params = array()) {
        return $this->request('book/orders/level-3/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_book_orders_level_2($params = array()) {
        return $this->request('book/orders/level-2/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_user_balances($params = array()) {
        return $this->request('user/balances/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_user_fees_and_limits($params = array()) {
        return $this->request('user/fees-and-limits/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_user_statement($params = array()) {
        return $this->request('user/statement/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_user_statement_currency_code($params = array()) {
        return $this->request('user/statement/{currency_code}/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_user_trades($params = array()) {
        return $this->request('user/trades/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_orders($params = array()) {
        return $this->request('orders/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_orders_open($params = array()) {
        return $this->request('orders/open/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_orders_id($params = array()) {
        return $this->request('orders/{id}/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_orders_by_external_id_external_id($params = array()) {
        return $this->request('orders/by-external-id/{external_id}/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_deposits($params = array()) {
        return $this->request('deposits/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_withdrawals($params = array()) {
        return $this->request('withdrawals/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_withdrawals_estimate_fee_currency_code($params = array()) {
        return $this->request('withdrawals/estimate-fee/{currency_code}/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_wallets_is_internal($params = array()) {
        return $this->request('wallets/is-internal/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_wallets_balance($params = array()) {
        return $this->request('wallets/balance/', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_wallets_balance_date($params = array()) {
        return $this->request('wallets/balance/{date}/', 'private', 'GET', $params, null, null, array());
    }
    public function private_post_orders($params = array()) {
        return $this->request('orders/', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_withdrawals($params = array()) {
        return $this->request('withdrawals/', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_transactions_sync($params = array()) {
        return $this->request('transactions/sync/', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_ticket($params = array()) {
        return $this->request('ticket/', 'private', 'POST', $params, null, null, array());
    }
    public function private_delete_orders($params = array()) {
        return $this->request('orders/', 'private', 'DELETE', $params, null, null, array());
    }
    public function private_delete_orders_by_external_id($params = array()) {
        return $this->request('orders/by-external-id/', 'private', 'DELETE', $params, null, null, array());
    }
    public function private_delete_orders_all($params = array()) {
        return $this->request('orders/all/', 'private', 'DELETE', $params, null, null, array());
    }
    public function publicGetTickers($params = array()) {
        return $this->request('tickers/', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetTickersPair($params = array()) {
        return $this->request('tickers/{pair}/', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetOrdersLevel3($params = array()) {
        return $this->request('orders/level-3/', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetOrdersLevel2($params = array()) {
        return $this->request('orders/level-2/', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetTrades($params = array()) {
        return $this->request('trades/', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetCurrencies($params = array()) {
        return $this->request('currencies/', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetPairs($params = array()) {
        return $this->request('pairs/', 'public', 'GET', $params, null, null, array());
    }
    public function privateGetBookSummaries($params = array()) {
        return $this->request('book/summaries/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetBookEstimatePricePair($params = array()) {
        return $this->request('book/estimate-price/{pair}/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetBookOrdersLevel3($params = array()) {
        return $this->request('book/orders/level-3/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetBookOrdersLevel2($params = array()) {
        return $this->request('book/orders/level-2/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetUserBalances($params = array()) {
        return $this->request('user/balances/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetUserFeesAndLimits($params = array()) {
        return $this->request('user/fees-and-limits/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetUserStatement($params = array()) {
        return $this->request('user/statement/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetUserStatementCurrencyCode($params = array()) {
        return $this->request('user/statement/{currency_code}/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetUserTrades($params = array()) {
        return $this->request('user/trades/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetOrders($params = array()) {
        return $this->request('orders/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetOrdersOpen($params = array()) {
        return $this->request('orders/open/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetOrdersId($params = array()) {
        return $this->request('orders/{id}/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetOrdersByExternalIdExternalId($params = array()) {
        return $this->request('orders/by-external-id/{external_id}/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetDeposits($params = array()) {
        return $this->request('deposits/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetWithdrawals($params = array()) {
        return $this->request('withdrawals/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetWithdrawalsEstimateFeeCurrencyCode($params = array()) {
        return $this->request('withdrawals/estimate-fee/{currency_code}/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetWalletsIsInternal($params = array()) {
        return $this->request('wallets/is-internal/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetWalletsBalance($params = array()) {
        return $this->request('wallets/balance/', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetWalletsBalanceDate($params = array()) {
        return $this->request('wallets/balance/{date}/', 'private', 'GET', $params, null, null, array());
    }
    public function privatePostOrders($params = array()) {
        return $this->request('orders/', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostWithdrawals($params = array()) {
        return $this->request('withdrawals/', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostTransactionsSync($params = array()) {
        return $this->request('transactions/sync/', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostTicket($params = array()) {
        return $this->request('ticket/', 'private', 'POST', $params, null, null, array());
    }
    public function privateDeleteOrders($params = array()) {
        return $this->request('orders/', 'private', 'DELETE', $params, null, null, array());
    }
    public function privateDeleteOrdersByExternalId($params = array()) {
        return $this->request('orders/by-external-id/', 'private', 'DELETE', $params, null, null, array());
    }
    public function privateDeleteOrdersAll($params = array()) {
        return $this->request('orders/all/', 'private', 'DELETE', $params, null, null, array());
    }
}
